gitlabUrl: https://gitlab.com/
runnerRegistrationToken: GR1348941wy9i6Kdg8nLrHGhc5Z8s

rbac:
  create: true

serviceAccount:
  create: true
  name: gitlab-runner

runners:
  privileged: true
  image: alpine
  namespace: default
  tags: minikube
  config: |
    [[runners]]
      name = "kubernetes-runner"
      url = "https://gitlab.com/"
      token = "glrt-nKWNJICq"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "default"
        image = "alpine"
        privileged = true
        service_account = "gitlab-runner"
        [[runners.kubernetes.volumes.host_path]]
          name = "docker-sock"
          mount_path = "/var/run/docker.sock"
          host_path = "/var/run/docker.sock"