gitlabUrl: https://gitlab.com/
runnerRegistrationToken: GR1348941wy9i6Kdg8nLrHGhc5Z8s

rbac:
  create: true

serviceAccount:
  create: true
  name: gitlab-runner

runners:
  privileged: true
  image: alpine
  namespace: default
  tags: minikube
  config: |
    [[runners]]
      name = "docker-runner"
      url = "https://gitlab.com/"
      token = "glrt-nKWNJICq"
      executor = "docker"
      [runners.docker]
        image = "alpine"
        privileged = true
        volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]